#!/usr/bin/env python3
# cargo-lock-add.py
#
# Usage: ./# cargo-lock-add.py CARGO-LOCK-BASE CARGO-LOCK-ADD > Cargo.lock
#

import sys
import tomllib

cargo_lock_base_file = sys.argv[1]
cargo_lock_add_file  = sys.argv[2]

def make_toml(value, depth=0):
	if type(value) is bool:
		return str(value).lower()
	elif type(value) is str:
		return f'"{value}"'
	elif type(value) is list:
		if depth <= 2:
			return "[\n" + "".join([" " + make_toml(x, depth + 1) + ",\n" for x in value]) + "]"
		else:
			return "[" + ", ".join([make_toml(x, depth + 1) for x in value]) + "]"
	elif type(value) is dict:
		field_list = [f"{k} = {make_toml(v, depth + 1)}" for k, v in value.items()]
		if depth == 1:
			return "\n".join(field_list)
		else:
			return "[" + ", ".join(field_list) + "]"
	else:
		assert False, f"Unhandled type {type(value)}"

with open(cargo_lock_base_file, "rb") as f:
	cargo_lock_base = tomllib.load(f)
with open(cargo_lock_add_file,  "rb") as f:
	cargo_lock_add  = tomllib.load(f)

base_packages = set()
base_count = len(cargo_lock_base["package"])

print(f"{base_count} packages in base lock file.", file=sys.stderr)

for package in cargo_lock_base["package"]:
	name = package["name"]
	version = package["version"]
	base_packages.add((name, version))

add_packages = []
add_count = len(cargo_lock_add["package"])

print(f"{add_count} packages in addendum lock file.", file=sys.stderr)

for package in cargo_lock_add["package"]:
	name = package["name"]
	version = package["version"]
	if (name, version) not in base_packages:
		add_packages.append(package)

print(f"{len(add_packages)} packages in the latter that are not present in the former.", file=sys.stderr)

assert len(add_packages) > 0, "There should be at least one!"

print()
print("# Addendum generated by cargo-lock-add.py")

for package in add_packages:
	name = package["name"]
	print()
	print("[[package]]")
	print(make_toml(package, 1))

# end cargo-lock-add.py
