# Makefile for chromium-adblock

CHROMIUM_SRC = /external/tmp/chromium/chromium-149.0.7827.196
RUST_SYSROOT = /usr/lib/rust-1.91

run_gnrt := tools/crates/run_gnrt.py \
	$(if $(RUST_SYSROOT),--rust-sysroot $(RUST_SYSROOT))

rust_dir = $(CHROMIUM_SRC)/third_party/rust

# Just a random file in the Chromium source tree
chromium_tree = $(CHROMIUM_SRC)/chrome/BUILD.gn

export LC_COLLATE = C

ci: apply-core-patch apply-src build-gnrt re-vendor gen-build-gn tarball patches

apply-core-patch: $(chromium_tree)
	touch $(CHROMIUM_SRC)/chromium-adblock.ci.stamp
	patch -p1 -d $(CHROMIUM_SRC) < core.patch

apply-src: $(chromium_tree)
	tar chf - -C src . | tar xf - -C $(CHROMIUM_SRC)
	test -f $(CHROMIUM_SRC)/chrome/browser/brave_shields/BUILD.gn

build-gnrt: $(chromium_tree)
	pkg-config --version
	pkg-config --libs openssl
	cd $(CHROMIUM_SRC) && $(run_gnrt) help

re-vendor: $(chromium_tree)
# Verify that adblock was patched into the Cargo.toml file
	grep -Fqx '[dependencies.adblock]' $(rust_dir)/chromium_crates_io/Cargo.toml
#
# Make a backup copy of the Rust subtree
	test -d $(rust_dir).orig || cp -a $(rust_dir) $(rust_dir).orig
#
# Add a dummy adblock entry to the Cargo.lock file
# (required for the next step to work)
	(echo; \
	 echo '[[package]]'; \
	 echo 'name = "adblock"'; \
	 echo 'version = "0.0.0"'; \
	 echo 'source = "registry+https://github.com/rust-lang/crates.io-index"'; \
	) >> $(rust_dir)/chromium_crates_io/Cargo.lock
#
# Update the Cargo.lock file ONLY for adblock
	cd $(CHROMIUM_SRC) && $(run_gnrt) update adblock
#
# Update the set of vendored crates
	cd $(CHROMIUM_SRC) && $(run_gnrt) vendor

# Generate the BUILD.gn files associated with each crate
gen-build-gn: $(chromium_tree)
	gn --version
	cd $(CHROMIUM_SRC) && $(run_gnrt) gen

# Generate tarball of the additional vendored crates needed by adblock
tarball: $(chromium_tree)
	test -d $(rust_dir).orig
	(cd $(CHROMIUM_SRC) && for crate in \
		third_party/rust/chromium_crates_io/vendor/* ; \
	 do \
		test -f $$crate/Cargo.toml || continue; \
		orig_crate=$$(echo "$$crate" | sed 's:/rust/:/rust.orig/:'); \
		test ! -d $$orig_crate \
		|| ! cmp -s $$crate/Cargo.toml $$orig_crate/Cargo.toml \
		|| continue; \
		echo $$crate; \
	 done \
	) > tmp.include.txt
	@echo "Generating tarball with $$(wc -l < tmp.include.txt) new/de-placeholder-ed crates:"
	timestamp=$$(cat $(CHROMIUM_SRC)/build/util/LASTCHANGE.committime) && \
	tar cJf chromium-adblock-rust-vendor.tar.xz \
		--owner=0 \
		--group=0 \
		--sort=name \
		--mtime=@$$timestamp \
		-C $(CHROMIUM_SRC) \
		third_party/rust/chromium_crates_io/Cargo.lock \
		-T tmp.include.txt
	rm tmp.include.txt

patches: chromium-adblock-src.patch chromium-adblock-rust.patch

# Collect the source files under src/ into a patch that creates them
chromium-adblock-src.patch:
	rm -rf tmp.empty tmp.src
	mkdir tmp.empty
	cp -rL src tmp.src
	(echo 'This patch is generated from the source code under src/ in the'; \
	 echo 'chromium-adblock project. Please do not edit this file directly.'; \
	 echo; \
	) > tmp.diff
	! git diff --no-index tmp.empty tmp.src >> tmp.diff
	sed -r '/^(diff|---|\+\+\+) / s: ([ab])/tmp\.src/: \1/:g' tmp.diff > $@
	rm -r tmp.empty tmp.src tmp.diff

# Generate patch to modify the GN files for individual Rust crates
chromium-adblock-rust.patch: $(chromium_tree)
	test -d $(rust_dir).orig
	rm -rf tmp.rust-patch-?
	mkdir tmp.rust-patch-a tmp.rust-patch-b
	tar cf - -C $(rust_dir).orig --exclude ./chromium_crates_io . \
	| tar xf - -C tmp.rust-patch-a
	tar cf - -C $(rust_dir)      --exclude ./chromium_crates_io . \
	| tar xf - -C tmp.rust-patch-b
	find tmp.rust-patch-b -depth -type d -empty -delete
	for crate in $$(cd tmp.rust-patch-a && echo *); do \
		test -e tmp.rust-patch-b/$$crate || rm -r tmp.rust-patch-a/$$crate; \
	done
	(echo 'Modify the GN files under third_party/rust/ for chromium-adblock.'; \
	 echo 'Please do not edit this file directly, as it is machine-generated.'; \
	 echo; \
	) > tmp.diff
	! git diff --no-index --no-renames \
		-I'^(Shipped|Security Critical): (no|yes)$$' \
		tmp.rust-patch-a tmp.rust-patch-b \
	>> tmp.diff
	sed -r '/^(diff|---|\+\+\+) / s:/tmp\.rust-patch-[ab]/:/third_party/rust/:g' tmp.diff > $@
	rm -r tmp.rust-patch-? tmp.diff

test_build_targets = chrome chrome_sandbox content_shell chromedriver headless_shell
test_build_subdir  = out/Release

# Partial test build (only Rust components and adblock-related objects)
test-build: $(chromium_tree) $(CHROMIUM_SRC)/$(test_build_subdir)/args.gn
	(cd $(CHROMIUM_SRC) && ninja -n -C $(test_build_subdir) $(test_build_targets)) > tmp.steps.txt
	grep -Eq ' CXX \S+/brave_adblock_ui\.o$$' tmp.steps.txt
	awk '/ RUST | CXX \S+(adblock|brave|cosmetic)/ { print $$3 }' tmp.steps.txt > tmp.objects.txt
	@echo "$$(wc -l < tmp.objects.txt) top-level objects in partial test build."
	(cd $(CHROMIUM_SRC) && ninja -C $(test_build_subdir) $$(cat $(CURDIR)/tmp.objects.txt))
	@echo 'Partial test build passed.'

user_files = \
	core.patch \
	chromium-adblock-src.patch \
	chromium-adblock-rust.patch \
	chromium-adblock-rust-vendor.tar.xz

# The steps a developer-user would follow to integrate chromium-adblock
# into their (pristine) Chromium source tree
user-process: $(user_files) $(chromium_tree)
	test ! -f $(CHROMIUM_SRC)/chromium-adblock.ci.stamp
	patch -p1 -d $(CHROMIUM_SRC) < core.patch
	patch -p1 -d $(CHROMIUM_SRC) < chromium-adblock-src.patch
	patch -p1 -d $(CHROMIUM_SRC) < chromium-adblock-rust.patch
	tar xJf chromium-adblock-rust-vendor.tar.xz -C $(CHROMIUM_SRC)
	@echo 'Chromium source is ready for configuration and building.'

clean:
	rm -rf tmp.empty
	rm -rf tmp.rust-patch-?
	rm -rf tmp.src
	rm -f tmp.*

clean-more: clean
	rm -f chromium-adblock-*.patch
	rm -f chromium-adblock-rust-vendor.tar.xz

# end Makefile
