# Makefile for chromium-adblock

CHROMIUM_SRC = /external/tmp/chromium/chromium-149.0.7827.196
RUST_SYSROOT = /usr/lib/rust-1.91

CARGO = $(RUST_SYSROOT)/bin/cargo

CP = cp

run_gnrt := tools/crates/run_gnrt.py \
	$(if $(RUST_SYSROOT),--rust-sysroot $(RUST_SYSROOT))

rust_dir = $(CHROMIUM_SRC)/third_party/rust

cr_timestamp := $(shell cat $(CHROMIUM_SRC)/build/util/LASTCHANGE.committime)

tar_opts = --owner=0 --group=0 --sort=name --mtime=@$(cr_timestamp)

ci: apply-core-patch apply-src build-gnrt re-vendor gen-build-gn tarball patches

apply-core-patch:
	patch -p1 -d $(CHROMIUM_SRC) < core.patch

apply-src:
	test -f $(CHROMIUM_SRC)/chrome/BUILD.gn
	cd src && find . -xtype f -exec $(CP) --parents {} $(CHROMIUM_SRC) \;

build-gnrt:
	pkg-config --version
	pkg-config --libs openssl
	cd $(CHROMIUM_SRC) && $(run_gnrt) help

re-vendor:
# Make sure that adblock was patched into the Cargo.toml file
	grep -Fqx '[dependencies.adblock]' $(rust_dir)/chromium_crates_io/Cargo.toml
#
# Make a backup copy of the Rust subtree
	test -d $(rust_dir).orig || cp -a $(rust_dir) $(rust_dir).orig
#
# Generate a temporary Cargo.toml file that pins crate versions
	./cargo-toml-pin.py $(rust_dir)/chromium_crates_io > tmp.Cargo.toml
#
# Copy in that Cargo.toml file and re-generate the dependency graph
	cp tmp.Cargo.toml $(rust_dir)/chromium_crates_io/Cargo.toml
	cd $(CHROMIUM_SRC) && $(run_gnrt) update
	cp $(rust_dir)/chromium_crates_io/Cargo.lock tmp.Cargo.lock
#
# Restore the original Cargo.toml and .lock files
	cp \
		$(rust_dir).orig/chromium_crates_io/Cargo.toml \
		$(rust_dir).orig/chromium_crates_io/Cargo.lock \
		$(rust_dir)/chromium_crates_io/
#
# Add all the new packages needed for adblock to the Cargo.lock file
	./cargo-lock-add.py \
		$(rust_dir).orig/chromium_crates_io/Cargo.lock \
		tmp.Cargo.lock \
	>> $(rust_dir)/chromium_crates_io/Cargo.lock
#
# Vendor the required crates; this will also clean up the Cargo.lock file
	cd $(CHROMIUM_SRC) && $(run_gnrt) vendor
#
# Check the new Cargo.lock file against the original one; the diff should
# be 99% new lines being added, so we look at the line subtractions
	! diff -u \
		$(rust_dir).orig/chromium_crates_io/Cargo.lock \
		$(rust_dir)/chromium_crates_io/Cargo.lock \
	| grep '^-' | grep -v '^--- ' \
	| grep -Ev '^- "[^ ",]+",$$'

# Generate the BUILD.gn files associated with each crate
gen-build-gn:
	gn --version
	cd $(CHROMIUM_SRC) && $(run_gnrt) gen

tarball:
	test -d $(rust_dir).orig
	(cd $(CHROMIUM_SRC) && for crate in \
		third_party/rust/chromium_crates_io/vendor/* ; \
	 do \
		test -f $$crate/Cargo.toml || continue; \
		orig_crate=$$(echo "$$crate" | sed 's:/rust/:/rust.orig/:'); \
		test ! -d $$orig_crate \
		|| ! cmp -s $$crate/Cargo.toml $$orig_crate/Cargo.toml \
		|| continue; \
		echo $$crate; \
	 done \
	) > tmp.include.txt
	@echo "Generating tarball with $$(wc -l < tmp.include.txt) new/de-placeholder-ed crates:"
	tar cJf chromium-adblock-rust-vendor.tar.xz $(tar_opts) \
		-C $(CHROMIUM_SRC) \
		third_party/rust/chromium_crates_io/Cargo.lock \
		-T tmp.include.txt
	rm tmp.include.txt

patches: chromium-adblock-src.patch chromium-adblock-rust.patch

# Collect the source files under src/ into a patch that creates them
chromium-adblock-src.patch:
	rm -rf tmp.empty tmp.src
	mkdir tmp.empty
	cp -rL src tmp.src
	(echo 'This patch is generated from the source code under src/ in the'; \
	 echo 'chromium-adblock project. Please do not edit this file directly.'; \
	 echo; \
	) > tmp.diff
	! git diff --no-index tmp.empty tmp.src >> tmp.diff
	sed -r '/^(diff|---|\+\+\+) / s: ([ab])/tmp\.src/: \1/:g' tmp.diff > $@
	rm -r tmp.empty tmp.src tmp.diff

# Generate patch to modify the GN files for individual Rust crates
chromium-adblock-rust.patch:
	test -d $(rust_dir).orig
	rm -rf tmp.rust-patch-?
	mkdir tmp.rust-patch-a tmp.rust-patch-b
	tar cf - -C $(rust_dir).orig --exclude ./chromium_crates_io . \
	| tar xf - -C tmp.rust-patch-a
	tar cf - -C $(rust_dir)      --exclude ./chromium_crates_io . \
	| tar xf - -C tmp.rust-patch-b
	find tmp.rust-patch-b -depth -type d -empty -delete
	for crate in $$(cd tmp.rust-patch-a && echo *); do \
		test -e tmp.rust-patch-b/$$crate || rm -r tmp.rust-patch-a/$$crate; \
	done
	printf 'Modify the GN files under third_party/rust/ for chromium-adblock.\n\n' > tmp.diff
	! git diff --no-index --no-renames \
		-I'^(Shipped|Security Critical): (no|yes)$$' \
		tmp.rust-patch-a tmp.rust-patch-b \
	>> tmp.diff
	sed -r '/^(diff|---|\+\+\+) / s:/tmp\.rust-patch-[ab]/:/third_party/rust/:g' tmp.diff > $@
	rm -r tmp.rust-patch-? tmp.diff

test_build_targets = chrome chrome_sandbox content_shell chromedriver headless_shell
test_build_subdir  = out/Release

# Partial test build (only Rust components and adblock-related objects)
test-build:
	test -f $(CHROMIUM_SRC)/$(test_build_subdir)/args.gn
	(cd $(CHROMIUM_SRC) && ninja -n -C $(test_build_subdir) $(test_build_targets)) > tmp.steps.txt
	grep -Eq ' CXX \S+/brave_adblock_ui\.o$$' tmp.steps.txt
	awk '/ RUST | CXX \S+(adblock|brave|cosmetic)/ { print $$3 }' tmp.steps.txt > tmp.objects.txt
	@echo "$$(wc -l < tmp.objects.txt) top-level objects in partial test build."
	(cd $(CHROMIUM_SRC) && ninja -C $(test_build_subdir) $$(cat $(CURDIR)/tmp.objects.txt))
	@echo 'Partial test build passed.'

user_files = \
	core.patch \
	chromium-adblock-src.patch \
	chromium-adblock-rust.patch \
	chromium-adblock-rust-vendor.tar.xz

# The steps a developer-user would follow to integrate chromium-adblock
# into their (pristine) Chromium source tree
user-process: $(user_files)
	patch -p1 -d $(CHROMIUM_SRC) < core.patch
	patch -p1 -d $(CHROMIUM_SRC) < chromium-adblock-src.patch
	patch -p1 -d $(CHROMIUM_SRC) < chromium-adblock-rust.patch
	tar xJf chromium-adblock-rust-vendor.tar.xz -C $(CHROMIUM_SRC)
	@echo 'Chromium source is ready for configuration and building.'

clean:
	rm -rf tmp.empty
	rm -rf tmp.rust-patch-?
	rm -rf tmp.src
	rm -f tmp.*

clean-more: clean
	rm -f chromium-adblock-*.patch
	rm -f chromium-adblock-rust-vendor.tar.xz

# end Makefile
